### ISSUE TITLE
New-ScreenShot has been blocked by your antivirus software

### ISSUE THREAD

**Issue by lboening** [riedyw/PoshFunctions#3]
I saved the module from PSGallery. I got a message from my computer:

import-module -name c:\alldata\poshfunctions

```shell


ParserError: C:\alldata\PoshFunctions\2.2.7\Functions\New-Screenshot.ps1:1
Line |
   1 |  function New-ScreenShot {
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | This script contains malicious content and has been blocked by your antivirus software.
```

**Comment by lboening** [comment]
On August 2, 2023, I still get same error through our anti-malware-detection-apparatus.

**Comment by riedyw** [comment]
I will place a NOTES: in the comment based help that some anti-malware software will block the function
