### ISSUE TITLE
[REQUEST] Move-Item with directory merging

### ISSUE THREAD

**Issue by God-damnit-all** [riedyw/PoshFunctions#4]
Either as a proxy command to Move-Item or a new command entirely, I'd like a Move-Item command capable of merging a moved directory to an already existing one.

The current work around is using Copy-Item instead and using Remove-Item afterward, but this is much slower.

**Comment by riedyw** [comment]
Can you elaborate your request with more detail and perhaps some examples?

**Comment by riedyw** [comment]
Outside of the scope of the module
