### ISSUE TITLE
Get-Font not dynamic ?

### ISSUE THREAD

**Issue by AntoineTurmel** [riedyw/PoshFunctions#8]
When I use Get-Font in a terminal, then install (or remove) a font, then re-run Get-Font, the list doesn't update to reflect it.
If I restart a powershell terminal it worked.

Any idea ?
Thanks.

**Comment by riedyw** [comment]
I was aware of that issue. Thanks for reminding me about it. I will place a NOTE: in the comment help

**Comment by riedyw** [comment]
Known issue
