### ISSUE TITLE
   New-ScreenShot  -Full  Unable to capture full screen 

### ISSUE THREAD

**Issue by ch-bob** [riedyw/PoshFunctions#9]
win 10.0.19045
New-ScreenShot.ps1  line-63
 if ($Full) {
    [Windows.Forms.Sendkeys]::SendWait('{PrtSc}')
 }
Change to 
[Windows.Forms.Sendkeys]::SendWait('+{PrtSc}')
Working normally

**Comment by riedyw** [comment]
The default behavior is to just capture the current active window. If you want to capture the full desktop you must specify -Full parameter
